### get all
GET https://e-pathshala-1wmr.onrender.com/courses
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>


### get published courses
GET https://e-pathshala-1wmr.onrender.com/courses/?filter=published
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>


### get archived courses
GET https://e-pathshala-1wmr.onrender.com/courses/?filter=archived
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>


### create
POST https://e-pathshala-1wmr.onrender.com/courses
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "courseName": "another test course",
  "description": "lorem posum"
}


### update
PUT https://e-pathshala-1wmr.onrender.com/courses/607288d1ed4dac369c62fcb7
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "status": "published",
  "description": "lorem posum"
}


### delete
DELETE https://e-pathshala-1wmr.onrender.com/courses/60726c6d940d5a33c8a5505c
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>


### enroll
POST https://e-pathshala-1wmr.onrender.com/courses/60324d08ba57d11e78c0dd66/enroll
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "userId": "6071299a5bf57641c44f84bd"
}


### unEnroll
POST https://e-pathshala-1wmr.onrender.com/courses/60324d08ba57d11e78c0dd66/un-enroll
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "userId": "6071299a5bf57641c44f84bd"
}
