GET https://e-pathshala-1wmr.onrender.com/deadlines
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>


### calendar
GET https://e-pathshala-1wmr.onrender.com/deadlines/calendar
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>
