### get all lectures
GET https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/lectures
Content-Type: application/json


### get all comments
GET https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/lectures/607c2205b035702c5cbc7ebe/comments
Content-Type: application/json


### create comment
POST https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/lectures/607c2205b035702c5cbc7ebe/comments
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "comment": "test comment 8"
}


### delete comment
DELETE https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/lectures/607c2205b035702c5cbc7ebe/comments/6084031c1b9fb72330e0757f
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>
