### GET all modules of a course
GET https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/modules
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

### GET module items for ONE module
GET https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/modules/607290a4835a88203427158d
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

### CREATE module
POST https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/modules
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "title": "Module 6"
}

### UPDATE module
PUT https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/modules/607290a4835a88203427158d
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
  "title": "Module 1"
}

### DELETE module
DELETE https://e-pathshala-1wmr.onrender.com/courses/6071bc6237d90440749b0d0c/modules/60728e6f2991c53e88e1b043
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>
