POST https://e-pathshala-1wmr.onrender.com/users/register
Content-Type: application/json

{
  "username": "admin",
  "name": "admin",
  "email": "admin@example.com",
  "password": "something",
  "passwordConfirm": "something",
  "code": "666666",
  "mobile": "0107537039",
  "agreement": true,
  "role": "admin"
}
